### ISSUE TITLE
Please bump fwupd to the next version (1.6.x)

### ISSUE THREAD

**Issue by LordChaos73** [pop-os/fwupd#6] opened 2021-09-04 09:59 UTC
**Describe the bug**
fwupd doesn't seem to work on Pop!OS 20.04

**Steps to Reproduce**
```shell
root@x1carbon6:~# fwupdmgr refresh
Updating lvfs
Downloading…             [***************************************]
Downloading…             [***************************************]
Failed to update metadata for lvfs: no signature method in results
```

**Expected behavior**
Updating the lvfs metadata should work fine.

**fwupd version information**
Please provide the version of the daemon and client.
```shell
root@x1carbon6:~# fwupdmgr --version
client version:	1.5.11
compile-time dependency versions
	gusb:	0.3.4
daemon version:	1.5.11
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
It came with the distrobution.

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
root@x1carbon6:~# fwupdmgr get-devices --show-all-devices
20KHCTO1WW
│
├─ThinkPad Thunderbolt 3 Dock:
│ │   Device ID:          4c354514fc888c1c9dc89dbb827a76d45ad33f02
│ │   Current version:    62.00
│ │   Vendor:             Lenovo (THUNDERBOLT:0x0108, TBT:0x0108)
│ │   GUIDs:              45c1814e-eb83-5b03-8997-ef8d4d8ade29 ← THUNDERBOLT\VEN_0108&DEV_1720&REV_00
│ │                       03b97e38-f4b8-5a19-917c-28f95ca29768 ← THUNDERBOLT\VEN_0108&DEV_1720
│ │                       75039175-c354-5df9-a798-5da41461c007 ← TBT-01081720
│ │   Device Flags:       • Updatable
│ │                       • System requires external power source
│ │                       • Device stages updates
│ │ 
│ ├─USB3.1 Hub:
│ │ │   Device ID:        7e452eb6c025449c23b67d34f76de2b1fdf4c815
│ │ │   Summary:          USB 3.x Hub
│ │ │   Current version:  51.63
│ │ │   Vendor:           VIA Labs, Inc. (USB:0x17EF)
│ │ │   Install Duration: 15 seconds
│ │ │   Serial Number:    00000000000000000000001
│ │ │   GUIDs:            8ee94f0e-9b44-596a-bdd9-6f90401664cc
│ │ │                     82aae1d4-67be-54c0-8256-ed2a7108650b ← USB\VID_17EF&PID_307F&REV_5163
│ │ │                     8aab7e9b-2ae8-559b-9be0-49bf5a647a2a ← USB\VID_17EF&PID_307F
│ │ │                     a9866465-e1ec-5ce0-855d-162d817aeca2 ← USB\VID_17EF&PID_307F&HUB_0002
│ │ │                     06fb2b19-690e-5296-8d0a-6e32a6fccd84 ← USB\VID_17EF&PID_307F&DEV_VL820Q7
│ │ │   Device Flags:     • Updatable
│ │ │                     • Cryptographic hash verification is available
│ │ │                     • Device stages updates
│ │ │                     • Device can recover flash failures
│ │ │ 
│ │ ├─USB3.1 Hub:
│ │ │ │   Device ID:      e487b5ff307494d6ff44d1b6dc1312bb69b0fe90
│ │ │ │   Summary:        USB 3.x Hub
│ │ │ │   Current version:51.33
│ │ │ │   Vendor:         VIA Labs, Inc. (USB:0x17EF)
│ │ │ │   Install Duration:15 seconds
│ │ │ │   Serial Number:  00000000000000000000001
│ │ │ │   GUIDs:          8ee94f0e-9b44-596a-bdd9-6f90401664cc
│ │ │ │                   3e9ec9de-6c88-520b-b768-d3839446d508 ← USB\VID_17EF&PID_307F&REV_5133
│ │ │ │                   8aab7e9b-2ae8-559b-9be0-49bf5a647a2a ← USB\VID_17EF&PID_307F
│ │ │ │                   672d37eb-2a8c-54fd-88f2-0faecea5f5e6 ← USB\VID_17EF&PID_307F&HUB_0006
│ │ │ │                   06fb2b19-690e-5296-8d0a-6e32a6fccd84 ← USB\VID_17EF&PID_307F&DEV_VL820Q7
│ │ │ │   Device Flags:   • Updatable
│ │ │ │                   • Cryptographic hash verification is available
│ │ │ │                   • Device stages updates
│ │ │ │                   • Device can recover flash failures
│ │ │ │ 
│ │ │ └─ThinkPad Thunderbolt 3 Dock USB Audio:
│ │ │       Device ID:    caee8370381dbe658ef9193b4948eb9ed1a25f8d
│ │ │       Summary:      CX20985 USB audio device
│ │ │       Current version:04-0E-92
│ │ │       Bootloader Version:02.00.00.00
│ │ │       Vendor:       Lenovo (USB:0x17EF)
│ │ │       Install Duration:3 seconds
│ │ │       Serial Number:0
│ │ │       GUIDs:        effe6afa-9e41-5ed0-b66e-dad13853a7bb ← USB\VID_17EF&PID_3083&REV_0092
│ │ │                     1d987aa4-e89a-5bd3-b78c-5ec8bdc6e213 ← SYNAPTICS_CXAUDIO\CX2098X
│ │ │                     d66bf84b-c3ba-508c-bc55-0d445413d3d4 ← USB\VID_17EF&PID_3083
│ │ │                     7083139e-9fec-5fc3-9e1a-a0fb3ae1bccf ← SYNAPTICS_CXAUDIO\CX20985
│ │ │       Device Flags: • Updatable
│ │ │     
│ │ └─MSP430:
│ │       Device ID:      3281dd62e64cfca4eec0492d675e1d4deb1b1cea
│ │       Summary:        I²C Dock Management Device
│ │       Current version:0.30
│ │       Vendor:         VIA Labs, Inc. (USB:0x17EF)
│ │       GUID:           7a810ce4-928e-5a4a-b0cd-564f46cfe3a7 ← USB\VID_17EF&PID_307F&I2C_MSP430
│ │       Device Flags:   • Updatable
│ │     
│ ├─USB2.0 Hub:
│ │ │   Device ID:        84d0e3f2a0f8b2328f7995767b23ebb40494723f
│ │ │   Summary:          USB 2.x Hub
│ │ │   Current version:  51.63
│ │ │   Vendor:           VIA Labs, Inc. (USB:0x17EF)
│ │ │   Install Duration: 15 seconds
│ │ │   Serial Number:    00000000000000000000001
│ │ │   GUIDs:            35199e34-cf82-5b09-9287-622d225056e4 ← USB\VID_17EF&PID_3080&REV_5163
│ │ │                     8ee94f0e-9b44-596a-bdd9-6f90401664cc ← USB\VID_17EF&PID_3080
│ │ │                     0987e3c9-b1ee-5763-ac6e-51329b034e4b ← USB\VID_17EF&PID_3080&HUB_20
│ │ │                     0488c1ec-e9d6-589f-8620-f0a7426a3c4e ← USB\VID_17EF&PID_3080&DEV_VL820Q7
│ │ │   Device Flags:     • Updatable
│ │ │                     • Cryptographic hash verification is available
│ │ │                     • Device stages updates
│ │ │                     • Device can recover flash failures
│ │ │ 
│ │ └─USB2.0 Hub:
│ │       Device ID:      0b3c94fad31628e8adddaad723b8b6b5e24a9665
│ │       Summary:        USB 2.x Hub
│ │       Current version:51.33
│ │       Vendor:         VIA Labs, Inc. (USB:0x17EF)
│ │       Install Duration:15 seconds
│ │       Serial Number:  00000000000000000000001
│ │       GUIDs:          a023c536-1f42-5215-9b66-1d330c939426 ← USB\VID_17EF&PID_3080&REV_5133
│ │                       8ee94f0e-9b44-596a-bdd9-6f90401664cc ← USB\VID_17EF&PID_3080
│ │                       1e96bd9e-b77e-5eb1-ba44-9c04a3d7c288 ← USB\VID_17EF&PID_3080&HUB_06
│ │                       0488c1ec-e9d6-589f-8620-f0a7426a3c4e ← USB\VID_17EF&PID_3080&DEV_VL820Q7
│ │       Device Flags:   • Updatable
│ │                       • Cryptographic hash verification is available
│ │                       • Device stages updates
│ │                       • Device can recover flash failures
│ │     
│ └─VMM5322:
│       Device ID:        d762543f8c20f636e6fff031a000078d3e10c600
│       Summary:          Multi-Stream Transport Device
│       Current version:  5.05.05
│       Vendor:           Synaptics (DRM_DP_AUX_DEV:0x06CB)
│       GUIDs:            e6b5bc25-d512-51b0-b23c-25fdf483b15d ← MST-595
│                         f15aa55c-9cd5-5942-85ae-a6bf8740b96c ← MST-panamera
│                         e0b67325-e8ff-5171-93e9-aaf098589166 ← MST-panamera-vmm5322-595
│                         50f72ec0-b147-56d7-b1a4-6af9256b2d6a ← MST-panamera-595
│       Device Flags:     • Updatable
│                         • Device stages updates
│     
├─Thunderbolt host controller:
│     Device ID:          c79c64c9b747477d0e99535b6892468de5cad634
│     Summary:            Unmatched performance for high-speed I/O
│     Current version:    43.00
│     Vendor:             Lenovo (THUNDERBOLT:0x0109, TBT:0x0109)
│     GUIDs:              e69c694c-de9f-5f9a-8d30-9b695ab4744b ← THUNDERBOLT\VEN_0109&DEV_1706&REV_00
│                         74e58157-171f-57bc-a660-bf467ded54cb ← THUNDERBOLT\VEN_0109&DEV_1706
│                         5ff9544e-fce2-5fd9-9cd2-671c95ac91dc ← TBT-01091706
│                         b8360cb5-b152-506a-9990-49d7bbbc3b88 ← TBT-01091706-controller0-0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Device stages updates
│   
├─Intel(R) Core™ i7-8550U CPU @ 1.80GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000ea
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│                         30249f37-d140-5d3e-9319-186b1bd5cac3 ← CPUID\PRO_0&FAM_06
│                         561403e8-143a-5071-ab09-bf5e4c146983 ← CPUID\PRO_0&FAM_06&MOD_8E
│                         54bdc429-0179-5019-9cb6-8a343324c97c ← CPUID\PRO_0&FAM_06&MOD_8E&STP_A
│     Device Flags:       • Internal device
│   
├─System Firmware:
│     Device ID:          1c53551e7da69d896138fac1ae131c83ad46d923
│     Current version:    65587
│     Minimum Version:    1
│     Vendor:             LENOVO (DMI:LENOVO)
│     GUIDs:              a4b51dca-8f97-4310-8821-3330f83c9135
│                         230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│                         6b3879ff-921f-5bc5-a0c2-5cec28f31d2f ← UEFI\RES_{A4B51DCA-8F97-4310-8821-3330F83C9135}
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Cryptographic hash verification is available
│                         • Device is usable for the duration of the update
│   
├─TPM:
│ │   Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Current version:    73.20.17568.6684
│ │   Vendor:             ST Microelectronics (TPM:STM)
│ │   GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│ │                       84df3581-f896-54d2-bd1a-372602f04c32 ← TPM\VEN_STM&DEV_0001
│ │                       bfaed10a-bbc1-525b-a329-35da2f63e918 ← TPM\VEN_STM&MOD_
│ │                       70b7b833-7e1a-550a-a291-b94a12d0f319 ← TPM\VEN_STM&DEV_0001&VER_2.0
│ │                       06f005e9-cb62-5d1a-82d9-13c534c53c48 ← TPM\VEN_STM&MOD_&VER_2.0
│ │   Device Flags:       • Internal device
│ │ 
│ └─Event Log:
│       Device ID:        58bd405f31c48e6eca290b425f530a94c91e955c
│       GUID:             a25657fe-b5dc-5be0-8b78-8b9dfec678ff ← system-tpm-eventlog
│       Device Flags:     • Internal device
│     
├─UEFI Device Firmware:
│     Device ID:          29749712e93b58730ecd1b8537a5503ff5b7fb27
│     Current version:    3092647749
│     Minimum Version:    3092647749
│     Vendor:             DMI:LENOVO
│     GUIDs:              9c9d9769-32fa-4841-b550-ea998e754e99
│                         1a4eea87-292a-5d99-82bd-fd244d4e0194 ← UEFI\RES_{9C9D9769-32FA-4841-B550-EA998E754E99}
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          9698faabddf0d7b18925cfbbda95f8b0d0dacc53
│     Current version:    65558
│     Minimum Version:    65558
│     Vendor:             DMI:LENOVO
│     GUIDs:              3babca5f-b2bf-4f4b-a72e-2bdc84eb4019
│                         7090c94a-ee40-593e-91bc-8cfd5a8c0a5d ← UEFI\RES_{3BABCA5F-B2BF-4F4B-A72E-2BDC84EB4019}
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          9e329270a7a68d289c82fe77d32d02208ddf0890
│     Current version:    4784148
│     Minimum Version:    4784148
│     Vendor:             DMI:LENOVO
│     GUIDs:              cea87551-1701-43fb-afbc-6e8ce9728345
│                         9ce4f5c8-e787-5f82-a7ef-a22c071c9423 ← UEFI\RES_{CEA87551-1701-43FB-AFBC-6E8CE9728345}
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UHD Graphics 620:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    07
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              2920038a-3772-52ef-8f3d-92c2fb1ac115 ← PCI\VEN_8086&DEV_5917&SUBSYS_17AA225C&REV_07
│                         0284ca6a-a235-5433-b190-1de21c753494 ← PCI\VEN_8086&DEV_5917&SUBSYS_17AA225C
│                         fed2efa4-7045-55a1-b4fc-b29283d59fe5 ← PCI\VEN_8086&DEV_5917&REV_07
│                         8b72a10c-1279-5f8e-a28a-34fb11a58240 ← PCI\VEN_8086&DEV_5917
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
└─WDC PC SN720 SDAQNTW-512G-1001:
      Device ID:          04e17fcf7d3de91da49a163ffe4907855c3648be
      Summary:            NVM Express Solid State Drive
      Current version:    10190101
      Vendor:             Sandisk Corp (NVME:0x15B7)
      Serial Number:      184873805566
      GUIDs:              06a6f1f7-4ce0-57ef-8154-0705d936e4a6 ← NVME\VEN_15B7&DEV_5002&SUBSYS_15B75002&REV_00
                          c528df4b-7972-5880-8cb1-330415e2dc6a ← NVME\VEN_15B7&DEV_5002&SUBSYS_15B75002
                          137520ce-3603-53e6-9165-56694ed744e7 ← NVME\VEN_15B7&DEV_5002&REV_00
                          ff2112dc-038c-596d-90ca-d43c5077c6ec ← NVME\VEN_15B7&DEV_5002
                          63af1441-fb24-5368-b450-886fbc98610b ← WDC PC SN720 SDAQNTW-512G-1001
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
```

**Additional questions**
- Operating system and version:
Pop!OS 20.04 (fully updated)
- Have you tried rebooting?
Yes
- Is this a regression?
Not that I'm aware of.

**Comment by mmstick** [comment] 2021-09-22 12:17
Duplicate of #7

**Closed as completed by mmstick** 2021-09-22 12:17 UTC
Labels: bug
